version: "2.1"
services:

  nginx:
    image: nginx:1.25.1-alpine
    container_name: nginx
    networks:
      - mynetwork
    volumes:
      - nginx-config:/etc/nginx
      - letsencrypt:/etc/letsencrypt
    ports:
      - 80:80
      - 443:443
    restart: unless-stopped

  vpn:
  ## Read https://github.com/qdm12/gluetun/wiki for details on configuring VPN for different service providers.
    # profiles: ["vpn"]
    container_name: vpn
    image: qmcgaw/gluetun:v3.35.0
    cap_add:
      - NET_ADMIN
    environment:
      - VPN_SERVICE_PROVIDER=protonvpn # Valid values: nordvpn, expressvpn, protonvpn, surfshark or custom
      - OPENVPN_USER=UbMXqF41SqkVqTrV
      - OPENVPN_PASSWORD=VTCg3cE81j1iANrDkbNFKXAUdpeZ0HcK
      - SERVER_COUNTRIES=Japan
      - FREE_ONLY=on  # Valid with protonvpn only. Value willbe set "on" if using free subscription provided by protonvpn
    networks:
      - mynetwork
    ports:
      # qbittorrent ports
      - 5080:5080
      - 6881:6881
      - 6881:6881/udp
      # prowlarr ports
      - 9696:9696 

  sonarr:
    image: lscr.io/linuxserver/sonarr:latest
    container_name: sonarr
    networks:
      - mynetwork    
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Asia/Kolkata
    volumes:
      - ${ConfigPath}/sonarr:/config
      - ${MediaPath}/data:/data
    ports:
      - 8989:8989
    restart: unless-stopped

  radarr:
    image: lscr.io/linuxserver/radarr:latest
    container_name: radarr
    networks:
      - mynetwork    
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Asia/Kolkata
    volumes:
      - ${ConfigPath}/radarr:/config
      - ${MediaPath}/data:/data
    ports:
      - 7878:7878
    restart: unless-stopped
    
  prowlarr:
    image: lscr.io/linuxserver/prowlarr:develop
    container_name: prowlarr
    depends_on:               
      - vpn                   
    network_mode: service:vpn 
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Asia/Kolkata
    volumes:
      - ${ConfigPath}/prowlarr:/config
    # ports:
    #   - 9696:9696
    restart: unless-stopped

  qbittorrent:
    image: lscr.io/linuxserver/qbittorrent:latest
    network_mode: service:vpn
    container_name: qbittorrent
    depends_on:
      - vpn        
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Asia/Kolkata
      - WEBUI_PORT=5080
    volumes:
      - ${ConfigPath}/qbittorrent:/config
      - ${MediaPath}/data/download:/data/download
    # ports:
    #   - 5080:5080
    #   - 6881:6881
    #   - 6881:6881/udp
    restart: unless-stopped

  jellyfin:
    image: lscr.io/linuxserver/jellyfin:latest
    container_name: jellyfin
    networks:
      - mynetwork    
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Etc/UTC
    volumes:
      - ${ConfigPath}/jellyfin:/config
      - ${MediaPath}/data/media/tv:/data/tvshows
      - ${MediaPath}/data/media/movies:/data/movies
    ports:
      - 8096:8096
    restart: unless-stopped

  # jackett:
  #   image: lscr.io/linuxserver/jackett:latest
  #   container_name: jackett
  #   environment:
  #     - PUID=1000
  #     - PGID=1000
  #     - TZ=Asia/Kolkata
  #   volumes:
  #     - ${ConfigPath}/jackett:/config
  #   ports:
  #     - 9117:9117
  #   restart: unless-stopped

  # flaresolverr:
  #   image: ghcr.io/flaresolverr/flaresolverr:latest
  #   container_name: flaresolverr
  #   environment:
  #     - LOG_LEVEL=${LOG_LEVEL:-info}
  #     - LOG_HTML=${LOG_HTML:-false}
  #     - CAPTCHA_SOLVER=${CAPTCHA_SOLVER:-none}
  #     - TZ=Asia/Kolkata
  #   ports:
  #     - "${PORT:-8191}:8191"
  #   restart: unless-stopped

networks:
  mynetwork:
    external: true

volumes:
  nginx-config:
  letsencrypt:    